---
- name: "Install packages"
  ansible.builtin.package:
    update_cache: true
    name:
      - "libpcre2-16-0"
      - "libpcre2-8-0"
      - "libpcre2-32-0"

- name: "Check if the /etc/pihole directory exist"
  register: file_check
  ansible.builtin.stat:
    path: "/etc/pihole"

- name: "Create /etc/pihole directory"
  when: not file_check.stat.exists
  ansible.builtin.file:
    path: "/etc/pihole"
    state: directory
    recurse: yes
    owner: "root"
    group: "root"
    mode: "0644"

- name: "Create / Set the password hash"
  register: install_pihole__webpassword_hashed
  changed_when: install_pihole__webpassword_hashed.rc != 0
  ansible.builtin.shell: >
    set -o pipefail
    echo -n {{ install_pihole__webpassword }} | sha256sum | awk '{printf "%s",$1 }' | sha256sum

- name: "Import setupVars configuration file"
  register: output
  changed_when: false 
  ansible.builtin.template:
    src: "templates/setupVars.conf.j2"
    dest: "/etc/pihole/setupVars.conf"
    lstrip_blocks: yes
    owner: "root"
    group: "root"
    mode: "0644"

- name: "Check /var/www/html/admin directory"
  register: file_check
  ansible.builtin.stat:
    path: "/var/www/html/admin"

- name: "Remove /var/www/html/admin directory"
  when: file_check.stat.exists and (install_pihole__force_install | default(false))
  register: output
  changed_when: (output.changed | default(false)) == false 
  ansible.builtin.file:
    path: "/var/www/html/admin"
    state: absent

- name: "Install PiHole"
  when: (install_pihole__force_install | default(false)) or (not (file_check.stat.exists))
  block:
    - name: "Install PiHole with bash"
      ansible.builtin.get_url:
        url: "https://install.pi-hole.net"
        dest: "/root/pihole_install.sh"
        owner: "root"
        mode: "0700"

    - name: "Run Pi-hole installer script"
      register: output
      changed_when: output.rc != 0
      ansible.builtin.shell: >
        bash /root/pihole_install.sh --unattended

- name: "Update PiHole with bash"
  register: ouput
  changed_when: ouput.rc != 0
  ansible.builtin.command: "/usr/local/bin/pihole -up"

- name: "Import adlists with bash"
  register: ouput
  changed_when: ouput.rc != 0
  when: install_pihole__adlists | default(false)
  loop: "{{ install_pihole__adlists }}"
  loop_control:
    loop_var: adlist
  ansible.builtin.command: "/usr/local/bin/pihole -a adlist add {{ adlist }}"

- name: "Import CNAME records"
  when: install_pihole__cname_list | default(false)
  register: cname_state
  notify: "Restart Pihole-FTL"
  ansible.builtin.template:
    src: "templates/05-pihole-custom-cname.conf.j2"
    dest: "/etc/dnsmasq.d/05-pihole-custom-cname.conf"
    lstrip_blocks: yes
    owner: "root"
    group: "root"
    mode: "0644"

- name: "Import AAAA records"
  when: install_pihole__aaaa_list | default(false)
  register: aaaa_state
  notify: "Restart Pihole-FTL"
  ansible.builtin.template:
    src: "templates/custom.list.j2"
    dest: "/etc/pihole/custom.list"
    lstrip_blocks: yes
    owner: "root"
    group: "root"
    mode: "0644"

- name: "Update Gravity with bash"
  register: ouput
  changed_when: ouput.rc != 0
  when: (cname_state.changed | default(false)) or (aaaa_state.changed | default(false))
  ansible.builtin.command: "/usr/local/bin/pihole -g"

- name: "Check /var/www/html/index.lighttpd.html directory"
  register: file_check
  ansible.builtin.stat:
    path: "/var/www/html/index.lighttpd.html"

- name: "Remove /var/www/html/index.lighttpd.html"
  when: file_check.stat.exists
  register: output
  changed_when: (output.changed | default(false)) == false 
  ansible.builtin.file:
    path: "/var/www/html/index.lighttpd.html"
    state: absent

- name: Set TTL in dnsmasq configuration
  notify: "Restart Pihole-FTL"
  ansible.builtin.lineinfile:
    path: /etc/dnsmasq.d/01-pihole.conf
    regexp: '^local-ttl='
    line: "local-ttl={{ install_pihole__ttl }}"

- name: "Set the password, as hard definition"
  register: output
  changed_when: output.rc != 0
  ansible.builtin.shell:
    pihole -a -p {{ install_pihole__webpassword }}
