---
- name: "Converge"
  hosts: "cicd-debian-11"
  tasks:

    - name: "Include labocbz.install_pihole"
      tags:
        - "labocbz.install_pihole"
      vars:
        install_pihole__webpassword: "{{ inv_install_pihole__webpassword }}"
        install_pihole__interface: "{{ inv_install_pihole__interface }}"
        install_pihole__ipv4_address: "{{ inv_install_pihole__ipv4_address }}"
        install_pihole__query_logging: "{{ inv_install_pihole__query_logging }}"
        install_pihole__install_web: "{{ inv_install_pihole__install_web }}"
        install_pihole__dnsmasq_listening: "{{ inv_install_pihole__dnsmasq_listening }}"
        install_pihole__dns_1: "{{ inv_install_pihole__dns_1 }}"
        install_pihole__dns_2: "{{ inv_install_pihole__dns_2 }}"
        install_pihole__dns_fqdn_required: "{{ inv_install_pihole__dns_fqdn_required }}"
        install_pihole__dns_bogus_priv: "{{ inv_install_pihole__dns_bogus_priv }}"
        install_pihole__dnssec: "{{ inv_install_pihole__dnssec }}"
        install_pihole__temperatureunit: "{{ inv_install_pihole__temperatureunit }}"
        install_pihole__webuiboxedlayout: "{{ inv_install_pihole__webuiboxedlayout }}"
        install_pihole__api_exclude_domains: "{{ inv_install_pihole__api_exclude_domains }}"
        install_pihole__api_exclude_clients: "{{ inv_install_pihole__api_exclude_clients }}"
        install_pihole__api_query_logs_show: "{{ inv_install_pihole__api_query_logs_show }}"
        install_pihole__api_privacy_mode: "{{ inv_install_pihole__api_privacy_mode }}"
        install_pihole__aaaa_list: "{{ inv_install_pihole__aaaa_list }}"
        install_pihole__cname_list: "{{ inv_install_pihole__cname_list }}"
        install_pihole__adlists: "{{ inv_install_pihole__adlists }}"
        install_pihole__force_install: "{{ inv_install_pihole__force_install }}"
        install_pihole__ttl: "{{ inv_install_pihole__ttl }}"
      ansible.builtin.include_role:
        name: "labocbz.install_pihole"
