---
- name: "Converge"
  hosts: "all"
  tasks:
    # replace these tasks with whatever you find suitable to test
    - name: "Copy something to test use of synchronize module"
      ansible.builtin.copy:
        src: "/etc/hosts"
        dest: "/tmp/hosts-from-controller"
        mode: 0700

    - name: "Include labocbz.install_pihole"
      tags:
        - "labocbz.install_pihole"
      vars:
        install_pihole_webpassword: "{{ inv_install_pihole_webpassword }}"
        install_pihole_interface: "{{ inv_install_pihole_interface }}"
        install_pihole_ipv4_address: "{{ inv_install_pihole_ipv4_address }}"
        install_pihole_query_logging: "{{ inv_install_pihole_query_logging }}"
        install_pihole_install_web: "{{ inv_install_pihole_install_web }}"
        install_pihole_dnsmasq_listening: "{{ inv_install_pihole_dnsmasq_listening }}"
        install_pihole_dns_1: "{{ inv_install_pihole_dns_1 }}"
        install_pihole_dns_2: "{{ inv_install_pihole_dns_2 }}"
        install_pihole_dns_fqdn_required: "{{ inv_install_pihole_dns_fqdn_required }}"
        install_pihole_dns_bogus_priv: "{{ inv_install_pihole_dns_bogus_priv }}"
        install_pihole_dnssec: "{{ inv_install_pihole_dnssec }}"
        install_pihole_temperatureunit: "{{ inv_install_pihole_temperatureunit }}"
        install_pihole_webuiboxedlayout: "{{ inv_install_pihole_webuiboxedlayout }}"
        install_pihole_api_exclude_domains: "{{ inv_install_pihole_api_exclude_domains }}"
        install_pihole_api_exclude_clients: "{{ inv_install_pihole_api_exclude_clients }}"
        install_pihole_api_query_logs_show: "{{ inv_install_pihole_api_query_logs_show }}"
        install_pihole_api_privacy_mode: "{{ inv_install_pihole_api_privacy_mode }}"
        install_pihole_aaaa_list: "{{ inv_install_pihole_aaaa_list }}"
        install_pihole_cname_list: "{{ inv_install_pihole_cname_list }}"
        install_pihole_adlists: "{{ inv_install_pihole_adlists }}"
        install_pihole_force_install: "{{ inv_install_pihole_force_install }}"
      ansible.builtin.include_role:
        name: "labocbz.install_pihole"
